### ISSUE TITLE
How to generate the same crystal structure as the input formula under the full strategy？

### ISSUE THREAD

**Issue by chachapro** [cyye001/Con-CDVAE#2]
When I use the full strategy for crystal generation, I cannot get the same crystal structure as the input formula, please help me to check if I have a problem with the parameters during training, or please tell me how to train the model so that the generated results are consistent with the input formula, thank you.
Here is my training code：
#step1
python concdvae/run.py train=new data=mptest expname=gap_full model=vae_mp_gap accelerator=gpu

#step2
python scripts/condition_diff_z.py --model_path /home/nbicc/data/cjh/Con-CDVAE/output/hydra/singlerun/2024-07-22/gap_full/ --model_file model_gap_full.pth --fullfea 1 --label chacha --newcond /home/nbicc/data/cjh/Con-CDVAE/conf/conz_2.yaml --newdata mptest4conz

#generate
python scripts/evaluate_diff.py --model_path "/home/nbicc/data/cjh/Con-CDVAE/output/hydra/singlerun/2024-07-22/gap_full/" --model_file model_gap_full.pth  --conz_file conz_model_chacha_diffu.pth --label chacha --prop_path general_full.csv

**Comment by chachapro** [comment]
Thank you for your reply.

**Comment by chachapro** [comment]
Whether there are some errors in the CS_type in the data set.
For example, MnF₂ and Ca5Pt3 are tetragonal, but their CS_type in the data set is 3 and 4, respectively.

**Comment by cyye001** [comment]
Ca5Pt3 and MnF2[mp-560902 or mp-615138] are tetragonal, but what I list in data set, MnF2[mp-556585], is orthorhombic. You may chack in Materials Project.

**Comment by chachapro** [comment]
Thank you for your reply！
