### ISSUE TITLE
Missing a `LICENSE` file within this repository

### ISSUE THREAD

**Issue by ZLI-afk** [cyye001/Con-CDVAE#5]
As noted, the current [Con-CDVAE](https://github.com/cyye001/Con-CDVAE) repo seems lack a `LICENSE` file to describe the copyright. Since it is developed based on [CDVAE](https://github.com/txie-93/cdvae), which includes an **MIT LICENSE**, the owner of the Con-CDVAE repo might consider adding one. This is recommended because the [MIT License](https://opensource.org/license/mit) stipulates that *'The copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.'*. Thanks.

**Comment by cyye001** [comment]
Thanks for your reminder, I have added MIT LICENSE to this project.
